model_name: "demonstration model"
model_version: 0.1
scenario_name: "test scenario"
location_options: "options.csv" 
option_id: "option_id"
draws: 30
land_uses:
  DU_add:
    name: "dwelling units added"
    market: "housing"
    store_fld: "hh_add"
    filter_fn: "(hh_init + hh_add - hh_del) <= (hh_cap - 1)" # passed to DataFrame.query()
    # value function is passed to DataFrame.eval()
    value_fn: >
      bid_logsum*0.1875826 + 
      intdens_N*1.5403721 +
      pct_sewer*0.0193174 + 
      is_MF*0.6578561 + 
      is_OR*3.2483276 + 
      elevation*4.9474182 + 
      avg_slope*-1.2718518 + 
      pct_water*0.3268022 + 
      elevation*pct_steep*-0.016281 + 
      elevation*is_MF*2.5527434 + 
      is_MF*avg_slope*-2.0949515 + 
      is_MF*pct_water*0.1972128 + 
      elevation*is_OR*-1.8275689 + 
      is_OR*avg_slope*0.2743983 + 
      is_OR*pct_water*-0.1399668
    total: 28407
  DU_del:
    name: "dwelling units removed"
    market: "housing"
    store_fld: "hh_del"
    filter_fn: "(hh_init + hh_add - hh_del) > 0" # passed to DataFrame.query()
    # value function is passed to DataFrame.eval()
    value_fn: >
      -1*(bid_logsum*0.1875826 + 
      intdens_N*1.5403721 +
      pct_sewer*0.0193174 + 
      is_MF*0.6578561 + 
      is_OR*3.2483276 + 
      elevation*4.9474182 + 
      avg_slope*-1.2718518 + 
      pct_water*0.3268022 + 
      elevation*pct_steep*-0.016281 + 
      elevation*is_MF*2.5527434 + 
      is_MF*avg_slope*-2.0949515 + 
      is_MF*pct_water*0.1972128 + 
      elevation*is_OR*-1.8275689 + 
      is_OR*avg_slope*0.2743983 + 
      is_OR*pct_water*-0.1399668)
    total: 9532
  EMP_add:
    name: "workspaces added"
    market: "business"
    store_fld: "ws_add"
    filter_fn: "(ws_init + ws_add - ws_del) <= (ws_cap - 1)"
    value_fn: >
      is_Commercial*-18.585542 + 
      is_Industrial*-17.409903 + 
      is_Institutional*-19.210086 + 
      is_Lodging*-22.494078 + 
      is_Mixed*-15.869786 + 
      is_Office*-19.374839 + 
      is_Special*-22.535318 + 
      pct_steep*-2.860402 + 
      pct_transit*1.403499 + 
      pct_water*0.194049 + 
      pct_sewer*0.09087 + 
      pct_steep*is_Industrial*0.335667 + 
      pct_transit*is_Industrial*-0.369398 + 
      pct_water*is_Industrial*0.03727 + 
      pct_sewer*is_Industrial*0.06423 + 
      pct_steep*is_Lodging*7.844066 + 
      pct_transit*is_Lodging*0.562455 + 
      pct_water*is_Lodging*2.680031 + 
      pct_sewer*is_Lodging*0.672675 + 
      pct_steep*is_Office*1.629512 + 
      pct_transit*is_Office*-0.581202 + 
      pct_water*is_Office*0.141043 + 
      pct_sewer*is_Office*1.499008 + 
      pct_steep*is_Other*1.427296 + 
      pct_transit*is_Other*-0.837501 + 
      pct_water*is_Other*0.292862
    total: 46768
  EMP_del:
    name: "workspaces removed"
    market: "business"
    store_fld: "ws_del"
    filter_fn: "(ws_init + ws_add - ws_del) >= 1"
    value_fn: >
      -1*(is_Commercial*-18.585542 + 
      is_Industrial*-17.409903 + 
      is_Institutional*-19.210086 + 
      is_Lodging*-22.494078 + 
      is_Mixed*-15.869786 + 
      is_Office*-19.374839 + 
      is_Special*-22.535318 + 
      pct_steep*-2.860402 + 
      pct_transit*1.403499 + 
      pct_water*0.194049 + 
      pct_sewer*0.09087 + 
      pct_steep*is_Industrial*0.335667 + 
      pct_transit*is_Industrial*-0.369398 + 
      pct_water*is_Industrial*0.03727 + 
      pct_sewer*is_Industrial*0.06423 + 
      pct_steep*is_Lodging*7.844066 + 
      pct_transit*is_Lodging*0.562455 + 
      pct_water*is_Lodging*2.680031 + 
      pct_sewer*is_Lodging*0.672675 + 
      pct_steep*is_Office*1.629512 + 
      pct_transit*is_Office*-0.581202 + 
      pct_water*is_Office*0.141043 + 
      pct_sewer*is_Office*1.499008 + 
      pct_steep*is_Other*1.427296 + 
      pct_transit*is_Other*-0.837501 + 
      pct_water*is_Other*0.292862)
    total: 17036
update_block: [
  "hh_final = hh_init + hh_add - hh_del",
  "ws_final = ws_init + ws_add - ws_del"
]