model_name: "demonstration model"
model_version: 0.1
scenario_name: "test scenario"
input_geos: "input_zones.shp"
product_types:
  SFH:
    name: "single-family dwelling units"
    market: "housing"
    # these field references can actually be any valid function passed to df.eval()
    inventory: "base_SFH"
    capacity: "SFH_cap"
    value_fn: "SFH_val"
    growth: 0
    decline: 0
  MFH:
    name: "multi-family dwelling units"
    market: "housing"
    inventory: "base_MFH"
    capacity: "MFH_cap"
    value_fn: "MFH_val"
    growth: 0
    decline: 0
  OFF:
    name: "office employment"
    market: "business"
    inventory: "base_OFF"
    capacity: "OFF_cap"
    value_fn: "OFF_val"    
    growth: 0
    decline: 0
  RET:
    name: "retail employment"
    market: "business"
    inventory: "base_RET"
    capacity: "RET_cap"
    value_fn: "RET_val"    
    growth: 0
    decline: 0
  IND:
    name: "industrial employment"
    market: "business"
    inventory: "base_IND"
    capacity: "IND_cap"
    value_fn: "IND_val"
    growth: 0
    decline: 0
  SVC:
    name: "service employment"
    market: "business"
    inventory: "base_SVC"
    capacity: "SVC_cap"
    value_fn: "SVC_val"
    growth: 0
    decline: 0
  EAF:
    name: "entertainment and food service jobs"
    market: "business"
    inventory: "base_EAF"
    capacity: "EAF_cap"
    value_fn: "EAF_val"
    growth: 0
    decline: 0
  ONR:
    name: "other non-residential activity"
    market: "business"
    inventory: "base_ONR"
    capacity: "ONR_cap"
    value_fn: "ONR_val"
    growth: 0
    decline: 0
